/**
 * Problem 2: Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var num = 4000000;
var result = 0;
var fib = [1, 2];
var currInd = 1;

function isEven(n) {
  return n % 2 === 0 ? true : false;
}

while (fib[currInd] < num) {
  if (isEven(fib[currInd])) {
    result += fib[currInd];
  }

  fib.push(fib[currInd] + fib[currInd-1]);
  currInd++;
}

console.log(result);
